services:
  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_PASS: ${ADMIN_PASS}
    volumes:
      - ./start.sh:/app/start.sh 
      - ./.env:/app/.env
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./notebooks:/app/notebooks
    ports:
      - "8001:8000"
    command: "sh -c 'chmod +x /app/start.sh && /app/start.sh'"
